### ISSUE TITLE
ResolutionImpossible: Cannot install blastradius==0.1.25 and flask==2.3.2

### ISSUE THREAD

**Issue by glasnt** [Ianyliu/blast-radius-fork#32]
```
ERROR: Cannot install blastradius==0.1.25 and flask==2.3.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    blastradius 0.1.25 depends on itsdangerous==2.0.1
    flask 2.3.2 depends on itsdangerous>=2.1.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

Introduced in #31 

Solution is to bump `itsdangerous` to match.

**Comment by Ianyliu** [comment]
I've merged your [pull request](https://github.com/Ianyliu/blast-radius-fork/pull/33)...
By the way, thank you so much for helping! 
I'm a student that has multiple part-time jobs taking maximum school credits so it's difficult for me to spend time on this..l would you like me to give you accessto the repository?

**Comment by glasnt** [comment]
Thank you for merging!

Don't worry about access. It was just one small change to make sure this fork worked for more people ✨

**Comment by Ianyliu** [comment]
Thanks! I hope more people contribute this because I personally do not use Terraform so it's a little hard for me to delegate more time to this project despite its many imperfections.
