### ISSUE TITLE
Dependency errors

### ISSUE THREAD

**Issue by chaoscreater** [Ianyliu/blast-radius-fork#36]
I've created a new venv and activated it. I then ran this:

`.\pip.exe install git+https://github.com/Ianyliu/blast-radius-fork`

And this is what I get:

`ERROR: Cannot install Flask, blastradius, blastradius==0.1.25 and werkzeug==2.3.6 because these package versions have conflicting dependencies.

The conflict is caused by:
    blastradius 0.1.25 depends on markupsafe==2.0.1
    jinja2 3.1.2 depends on MarkupSafe>=2.0
    werkzeug 2.3.6 depends on MarkupSafe>=2.1.1
    blastradius 0.1.25 depends on markupsafe==2.0.1
    jinja2 3.1.2 depends on MarkupSafe>=2.0
    werkzeug 2.3.5 depends on MarkupSafe>=2.1.1
    blastradius 0.1.25 depends on markupsafe==2.0.1
    jinja2 3.1.2 depends on MarkupSafe>=2.0
    werkzeug 2.3.4 depends on MarkupSafe>=2.1.1
    blastradius 0.1.25 depends on markupsafe==2.0.1
    jinja2 3.1.2 depends on MarkupSafe>=2.0
    werkzeug 2.3.3 depends on MarkupSafe>=2.1.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
`

If I do a pip list, there are no packages installed and I'm definitely in the venv. Seems like the packages that are trying to be installed have a dependency conflict with each other. It's looking for Markupsafe version 2.0.1 (first line) but also greater than 2.0.1...

I think your requirements.txt needs to update the dependency for markupsafe to >= 2.0.1.

**Comment by Ianyliu** [comment]
Thank you @chaoscreater !
