### ISSUE TITLE
Upload file not working

### ISSUE THREAD

**Issue by chaoscreater** [Ianyliu/blast-radius-fork#38]
I got this working in Docker using this:

```
docker run --rm -it -p 5000:5000 `
  -v ${pwd}:/data:ro `
  --security-opt apparmor:unconfined `
  --cap-add=SYS_ADMIN `
  ianyliu/blast-radius-fork --serve .
```

Where the . is my Terraform project folder.

However, I want to use the Upload file feature and tried all sorts of files and it's not accepting any of them as a valid file. What is the file supposed to be?

![image](https://github.com/Ianyliu/blast-radius-fork/assets/18227319/9ef1e939-91da-4f56-a87b-939eaf46a002)

**Comment by chaoscreater** [comment]
Never mind, managed to find some information in the main repo that this was forked from.

Run terraform graph and copy the output and save it into a .txt file, i.e a DOT script. For example:

```
digraph {
        compound = "true"
        newrank = "true"
        subgraph "root" {
                "[root] azurerm_key_vault.example (expand)" [label = "azurerm_key_vault.example", shape = "box"]
                "[root] azurerm_resource_group.example (expand)" [label = "azurerm_resource_group.example", shape = "box"]
                "[root] data.azurerm_client_config.current (expand)" [label = "data.azurerm_client_config.current", shape = "box"]
                "[root] provider[\"registry.terraform.io/hashicorp/azurerm\"]" [label = "provider[\"registry.terraform.io/hashicorp/azurerm\"]", shape = "diamond"]
                "[root] azurerm_key_vault.example (expand)" -> "[root] azurerm_resource_group.example (expand)"
                "[root] azurerm_key_vault.example (expand)" -> "[root] data.azurerm_client_config.current (expand)"
                "[root] azurerm_resource_group.example (expand)" -> "[root] provider[\"registry.terraform.io/hashicorp/azurerm\"]"
                "[root] data.azurerm_client_config.current (expand)" -> "[root] provider[\"registry.terraform.io/hashicorp/azurerm\"]"
                "[root] provider[\"registry.terraform.io/hashicorp/azurerm\"] (close)" -> "[root] azurerm_key_vault.example (expand)"
                "[root] root" -> "[root] provider[\"registry.terraform.io/hashicorp/azurerm\"] (close)"
        }
}

```

then just upload the text file. 

I basically tried everything except for the above.......I generated a JSON from Terraform Graph and uploaded the it, but that didn't work. I also generated a SVG from Terraform Graph and tried to upload that (yes I know it doesn't make sense as I'm using a graph to generate a graph with blast-radius). I also tried using the state file, didn't work either. I then tried using this to read the state file to output to JSON format - terraform show -json output.tfplan > output.json

Anyway, I think better and more instructions should be provided, as I had to find out about the DOT script as a comment somewhere else.

**Comment by Ianyliu** [comment]
@chaoscreater  Thank you for this! 
I have updated the README.md file. If you think it's still unclear, feel free to suggest further improvements!

https://github.com/Ianyliu/blast-radius-fork/pull/42
